### mysql连接信息
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    ### 数据源类别
    type: com.alibaba.druid.pool.DruidDataSource
    ### 初始化大小，最小，最大
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      ### 配置获取连接等待超时的时间，单位是毫秒
      max-wait: 60000
      ### 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      ### 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      ### 打开 PSCache,并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      ### 通过connectProperties属性来打开mergeSql功能,慢SQL记录
      connection-properties: true
      ### 配置监控统计拦截的filters，去掉后监控界面的SQL无法统计，‘wall’用于防火墙
      filter:
        wall:
        log4j:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      ### 合并多个DruidDataSource的监控数据
      #use-global-data-source-stat: true

  ### thymeleaf配置
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    ### 内容类别，可不用配置
    servlet:
      content-type: text/html
    ### 开发配置false,避免修改模板还要重启服务器
    cache: false
    ### 配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/

  ### redis缓存配置
  ### 默认 redis 缓存数据库为db0
  redis:
    database: 0
    ### 服务器地址,默认为localhost
    host: localhost
    ### 链接端口，默认是6379
    port: 6379

    ### redis默认密码为空
    password:
  ### Mail邮件配置
  ### 邮箱主机
  mail:
    host: smtp.qq.com
    ### 发送者邮箱
    username: 2533906024@qq.com
    ### 设置的授权码
    password: jkpxkfvnhtgwebde
    ### 默认编码
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
    ### 端口号465或587
    port: 587
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
    packages:
      trust-all: true

  ###mongodb配置
  ###host地址
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

server:
  port: 8088

logging:
  config: classpath:log4j2.xml
mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.lpy.dao

